title: Hello, world! I'm Eric McKinney.
description: > # this means to ignore newlines until "baseurl:"
  Music Production. Web Development. Project Management.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emckin.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/waitonce

# Author Settings
author: Eric McKinney # add your name
author-img: eric.png # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: mckinney99 # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
